### Import all of moduls

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from IPython.display import Image

### Import picture as case (vehicle routing problem in USA)

In [2]:
Image(url="https://miro.medium.com/max/1104/1*M8Bw2KFlfII5S3VTYNfdZA.png", width=500, height=500)

In [10]:
## Make a routing model
graph = {
    'Los Angeles':{'San Francisco':629,'Las Vegas':435},
    'San Francisco':{'Los Angeles':629,'Las Vegas':919,'Seattle':1306},
    'Las Vegas':{'Los Angeles':435,'San Francisco':919,'Denver':1225,'Dallas':1983},
    'Seattle':{'San Francisco':1306,'Denver':2161,'Minneapolis':2661},
    'Denver':{'Las Vegas':1225,'Seattle':2161,'Dallas':1258,'Minneapolis':1483},
    'Dallas':{'Las Vegas':1983,'Denver':1258,'Minneapolis':1532,'Miami':2161,'Washington DC':2113},
    'Minneapolis':{'Denver':1483,'Seattle':2661,'Dallas':1532,'Chicago':661},
    'Miami':{'Dallas':2161,'Washington DC':1709,'New York':2145},
    'Chicago':{'Minneapolis':661,'Washington DC':1145,'Boston':1613},
    'Washington DC':{'Dallas':2113,'Chicago':1145,'New York':383,'Miami':1709},
    'New York':{'Washington DC':383,'Miami':2145,'Boston':338},
    'Boston':{'Chicago':1613,'Washington DC':725,'New York':338}
}
graph
visited_vertex = [] ## visited vertex for a graph table
path = {}

## Decide an initial vertex and also target vertex
initial_vertex = 'Los Angeles'
visited_vertex_path = graph[initial_vertex]
visited_vertex.append(initial_vertex)
path[initial_vertex] = visited_vertex_path
target_vertex = 'Boston'
    
while target_vertex not in visited_vertex:
    previous_vertex = visited_vertex[-1]
    min_distance_vertex = min(path[previous_vertex].values())
    next_vertex_not_str = [i for i in path[previous_vertex] if path[previous_vertex][i] == min_distance_vertex]
    next_vertex = ''.join(next_vertex_not_str)
    if previous_vertex in graph[next_vertex]:
        del graph[next_vertex][previous_vertex]
    next_vertex_path = {}
    next_vertex_path.update(path[previous_vertex])
    for i in list(graph[next_vertex]):
        if i in visited_vertex:
            del graph[next_vertex][i]
        else:
            next_path = path[visited_vertex[-1]][next_vertex] + graph[next_vertex][i]
            next_vertex_path[i] = next_path
            if next_path > path[previous_vertex][next_vertex]:
                if i in graph[previous_vertex]:
                    next_path = path[previous_vertex][i]
                    next_vertex_path[i] = next_path
                else:
                    next_path = path[visited_vertex[-1]][next_vertex] + graph[next_vertex][i]
                    next_vertex_path[i] = next_path
            else:
                continue
    visited_vertex.append(next_vertex)
    path[next_vertex] = next_vertex_path
    if next_vertex in path[next_vertex]:
        del path[next_vertex][next_vertex]

target_vertex_path = {}
for i in path:
    if target_vertex in path[i]:
        target_vertex_path.update({i:path[i][target_vertex]})
    else:
        continue
for i in target_vertex_path:
    if target_vertex_path[i] == min(target_vertex_path.values()):
        vertex_before_target = i
target_vertex_path        
total_distance = path[vertex_before_target][target_vertex]

before_target_vertex_not_str = []
for i in target_vertex_path:
    if target_vertex_path[i] == min(target_vertex_path.values()):
        before_target_vertex_not_str.append(i)
        break
    else:
        continue
before_target_vertex = ''.join(before_target_vertex_not_str)
before_target_vertex

routing_from_target_vertex = [target_vertex,before_target_vertex]
j = routing_from_target_vertex[-1]
d_path = {}

while initial_vertex not in routing_from_target_vertex:
    j = routing_from_target_vertex[-1]
    d_path = {}
    for i in path:
        if routing_from_target_vertex[-1] in list(path[i]):
            d_path.update({i:path[i][routing_from_target_vertex[-1]]})
        else:
            continue
    for i in d_path:
        if d_path[i] == min(d_path.values()):
            routing_from_target_vertex.append(i)
            break
routing_from_target_vertex
routing_from_target_vertex.reverse()
routing_from_target_vertex

vertex_goal = pd.DataFrame({})
for i in graph:
    vertex_goal[i] = []
vertex_goal
for i in path:
    vertex_goal = vertex_goal.append(path[i],ignore_index=True)

for i in vertex_goal[initial_vertex]:
    vertex_goal[initial_vertex] = vertex_goal[initial_vertex].replace([i],0)
vertex_goal

import math

vertex_goal_list = []
for i in graph:
    vertex_goal_list.append(i)
vertex_goal_list

vertex_goal_2 = pd.DataFrame({})
for i in graph:
    vertex_goal_2[i] = []
vertex_goal_2

for i in vertex_goal_list[1:]:
    p = list(vertex_goal[i])
    len_not_nan = []
    v = 0
    for j in p:
        if math.isnan(j):
            v += 1
            continue
        else:
            len_not_nan.append(v)
            v += 1
    v = 0
    for k in p:
        if v > len_not_nan[-1]:
            p[v] = p[v-1]
            v += 1
        else:
            v += 1
            continue
    vertex_goal_2[i] = p

for i in vertex_goal_2[initial_vertex]:
    vertex_goal_2[initial_vertex] = vertex_goal_2[initial_vertex].replace([i],0)

print('')
print('Based on the graph table below, the shortest path routing is :',routing_from_target_vertex,'with the total distance is',total_distance,'unit of length')
print('')

vertex_goal_2.index = visited_vertex
vertex_goal = vertex_goal_2.fillna('Infinity') ## Infinity means if there's no direct routing for those city
vertex_goal.drop(index=vertex_goal.index[-1], 
        axis=0, 
        inplace=True)
vertex_goal

Based on the graph table below, the shortest path routing is : ['Los Angeles', 'Las Vegas', 'Denver', 'Minneapolis', 'Chicago', 'Boston'] with the total distance is 5417 unit of length

,Los Angeles,San Francisco,Las Vegas,Seattle,Denver,Dallas,Minneapolis,Miami,Chicago,Washington DC,New York,Boston
Los Angeles,0.0,629.0,435.0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity
Las Vegas,0.0,629.0,435.0,Infinity,1660.0,2418.0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity
San Francisco,0.0,629.0,435.0,1935.0,1660.0,2418.0,Infinity,Infinity,Infinity,Infinity,Infinity,Infinity
Denver,0.0,629.0,435.0,1935.0,1660.0,2918.0,3143.0,Infinity,Infinity,Infinity,Infinity,Infinity
Seattle,0.0,629.0,435.0,1935.0,1660.0,2918.0,3143.0,Infinity,Infinity,Infinity,Infinity,Infinity
Dallas,0.0,629.0,435.0,1935.0,1660.0,2918.0,3143.0,5079.0,Infinity,5031.0,Infinity,Infinity
Minneapolis,0.0,629.0,435.0,1935.0,1660.0,2918.0,3143.0,5079.0,3804.0,5031.0,Infinity,Infinity
Chicago,0.0,629.0,435.0,1935.0,1660.0,2918.0,3143.0,5079.0,3804.0,4949.0,Infinity,5417.0
Washington DC,0.0,629.0,435.0,1935.0,1660.0,2918.0,3143.0,6658.0,3804.0,4949.0,5332.0,5417.0
New York,0.0,629.0,435.0,1935.0,1660.0,2918.0,3143.0,6658.0,3804.0,4949.0,5332.0,5670.0